version: '3.4'

services:
    engapi:
        image: ${DOCKER_REGISTRY-}engapi
        build:
          context: .
          dockerfile: EngApi/Dockerfile
        ports:
            - "9080:80"
        depends_on: 
            - db
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          - SA_PASSWORD=SAPassword1!
          - ACCEPT_EULA=Y
        ports:
          - "5434:1433"